AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Amplify App for Polaris Frontend'

Parameters:
  RepositoryUrl:
    Type: String
    Description: GitHub repository URL
    Default: 'https://github.com/umair2602/polaris-rfp.git'

  BranchName:
    Type: String
    Description: Branch name to deploy
    Default: 'main'

  Environment:
    Type: String
    Description: Environment name
    Default: 'production'
    AllowedValues: ['development', 'staging', 'production']

  GitHubToken:
    Type: String
    Description: GitHub token for repository access
    NoEcho: true

  BackendUrl:
    Type: String
    Description: Backend API URL
    Default: 'https://cvsmuhhazj.us-east-1.awsapprunner.com'

  EnableCustomDomain:
    Type: String
    Description: Whether to create Amplify custom domain mapping
    Default: 'false'
    AllowedValues: ['true', 'false']

  CustomDomainName:
    Type: String
    Description: Root domain for Amplify custom domain mapping (e.g. polariseco.com)
    Default: 'polariseco.com'

  CustomDomainPrefix:
    Type: String
    Description: Subdomain prefix (e.g. rfp)
    Default: 'rfp'

Conditions:
  UseCustomDomain: !Equals [!Ref EnableCustomDomain, 'true']

Resources:
  # IAM Role for Amplify
  AmplifyServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: amplify.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess-Amplify

  # Amplify App
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: !Sub 'polaris-frontend-${Environment}'
      Repository: !Ref RepositoryUrl
      AccessToken: !Ref GitHubToken
      BuildSpec: |
        version: 1
        frontend:
          phases:
            preBuild:
              commands:
                - cd frontend
                - npm ci
          build:
            commands:
              - npm run build
        artifacts:
          baseDirectory: frontend/out
          files:
            - '**/*'
          cache:
            paths:
              - frontend/node_modules/**/*
              - frontend/.next/cache/**/*
      EnvironmentVariables:
        - Name: NODE_ENV
          Value: !Ref Environment
        - Name: API_BASE_URL
          Value: !Ref BackendUrl
        - Name: NEXT_PUBLIC_API_BASE_URL
          Value: !Ref BackendUrl
      CustomRules:
        - Source: '**'
          Target: '/index.html'
          Status: '200'
      Platform: WEB_COMPUTE

  # Amplify Branch
  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: !Ref BranchName
      Description: !Sub 'Main branch for ${Environment} environment'
      EnableAutoBuild: true
      EnablePullRequestPreview: true
      EnvironmentVariables:
        - Name: NODE_ENV
          Value: !Ref Environment
        - Name: API_BASE_URL
          Value: !Ref BackendUrl
        - Name: NEXT_PUBLIC_API_BASE_URL
          Value: !Ref BackendUrl

  # Amplify Domain (optional)
  AmplifyDomain:
    Condition: UseCustomDomain
    Type: AWS::Amplify::Domain
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      DomainName: !Ref CustomDomainName
      SubDomainSettings:
        - BranchName: !Ref BranchName
          Prefix: !Ref CustomDomainPrefix

Outputs:
  AmplifyAppId:
    Description: 'Amplify App ID'
    Value: !GetAtt AmplifyApp.AppId
    Export:
      Name: !Sub '${AWS::StackName}-AmplifyAppId'

  AmplifyAppUrl:
    Description: 'Amplify App URL'
    Value: !Sub 'https://${BranchName}.${AmplifyApp.DefaultDomain}'
    Export:
      Name: !Sub '${AWS::StackName}-AmplifyAppUrl'

  CustomDomainUrl:
    Description: 'Custom domain URL (if enabled)'
    Value: !If
      - UseCustomDomain
      - !Sub 'https://${CustomDomainPrefix}.${CustomDomainName}'
      - ''
    Export:
      Name: !Sub '${AWS::StackName}-CustomDomainUrl'

  AmplifyServiceRoleArn:
    Description: 'Amplify Service Role ARN'
    Value: !GetAtt AmplifyServiceRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-AmplifyServiceRoleArn'
